- docs/examples/thor-client/blocks.ts
- docs/templates/thor-client.md
- docs/thor-client.md
- packages/network/src/thor-client/blocks/blocks-module.ts
- packages/network/src/thor-client/blocks/types.d.ts
- packages/network/tests/thor-client/blocks/blocks.testnet.test.ts
- packages/network/tests/thor-client/transactions/transactions-thorest.testnet.test.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/evm_mine/evm_mine.ts
- packages/provider/tests/rpc-mapper/methods/eth_blockNumber/eth_blockNumber.solo.test.ts
- packages/provider/tests/rpc-mapper/methods/eth_blockNumber/eth_blockNumber.testnet.test.ts
- packages/provider/tests/rpc-mapper/methods/evm_mine/evm_mine.mock.solo.test.ts
Create compressed and expanded methods for getFinalBlock and waitForBlock.
> Create compressed and expanded methods in block module

- packages/network/src/thor-client/blocks/blocks-module.ts
> fix: coverage 100%

- packages/errors/src/utils/error-message-builder/error-message-builder.ts
- packages/errors/tests/utils/error-message-builder/error-message-builder.unit.test.ts
- packages/network/tests/thor-client/transactions/transactions.testnet.test.ts
Fix test running and revert some modifications
> fix: test running and revert modifications

- packages/network/tests/thor-client/transactions/transactions.testnet.test.ts
> fix: tests

- packages/provider/src/utils/const/blocks/blocks.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_call/eth_call.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_getBalance/eth_getBalance.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_getCode/eth_getCode.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_getStorageAt/eth_getStorageAt.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_getTransactionCount/eth_getTransactionCount.ts
- packages/provider/src/utils/rpc-mapper/types.d.ts
- packages/provider/tests/rpc-mapper/methods/eth_call/fixture.ts
- packages/provider/tests/rpc-mapper/methods/eth_getBalance/fixture.ts
Solve bug. Now we can use blockTag | { blockNumber: ... } | { blockHash: '0x...' } | '0x...'
> Quantity tag bug

- packages/network/src/thor-client/thor-client.ts
- packages/network/tests/thor-client/accounts/accounts.solo.test.ts
Add factory method to simplify Thor client usage
> feat:User friendly way of Thor client usage

- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_getBlockByHash/eth_getBlockByHash.ts
- packages/provider/src/utils/rpc-mapper/methods-map/methods/eth_syncing/eth_syncing.ts
- packages/provider/tests/rpc-mapper/methods/eth_getStorageAt/fixture.ts
Remove not needed // eslint-disable-next-line
> fix: remove some eslint-disable-next-line

- packages/network/src/thor-client/transactions/transactions-module.ts
- packages/network/src/thor-client/transactions/types.d.ts
- packages/network/tests/thor-client/transactions/transactions.mocks.solo.test.ts
In `transactions-module.ts`, the method `buildTransactionBody` allows to set any property of the resulting `TransactionBody` via argument `options?: TransactionBodyOptions`.
* Node.js Version: 21.6.2
* Yarn Version: v1.22.21
> 383 build transaction body add new fields to override

- README.md
The file `README.md` includes specific instructions to install the SDK on Windows OS.
* Node.js Version: v21.6.2
* Yarn Version: v1.22.21
> docs: #759 README.md includes additional instructions for Windows OS

- apps/sdk-nextjs-integration/README.md
- apps/sdk-nextjs-integration/src/app/globals.css
- apps/sdk-nextjs-integration/src/app/page.tsx
- apps/sdk-nextjs-integration/yarn.lock
Implement sdk-nextjs-integration test app
> Implement sdk-nextjs-integration test app

- apps/sdk-hardhat-integration/README.md
- apps/sdk-hardhat-integration/hardhat.config.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/type-extensions.ts
- packages/hardhat-plugin/tests/hardhat-mock-projects/simple-vechain-hardhat-project/hardhat.config.ts
- packages/hardhat-plugin/tests/simple-vechain-hardhat-project.solo.test.ts
- packages/network/src/provider/providers/hardhat-provider/hardhat-provider.ts
- packages/network/src/provider/providers/vechain-provider/vechain-provider.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_sendTransaction/eth_sendTransaction.ts
- packages/network/tests/provider/providers/vechain/vechain-provider.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_sendTransaction/eth_sendTransaction.solo.test.ts
- packages/rpc-proxy/config.json
- packages/rpc-proxy/src/index.ts
- packages/rpc-proxy/src/types.d.ts
> feat: add enableDelegation and convert debogMode to debug

- docs/accounts.md
- docs/examples/accounts/bip32.ts
- docs/examples/accounts/bip39.ts
- packages/core/src/mnemonic/mnemonic.ts
- packages/core/tests/mnemonic/fixture.ts
- packages/core/tests/mnemonic/mnemonic.unit.test.ts
BIP32 functionalities provided by `packages/core/src/mnemonic/mnemonic.ts` are 
pure - browser /nodejs agnostic
secure - pass a cryptographic security audit.
Method `mnemonic.validate` renamed `mnemonic.isValid`.
`docs/examples/accounts/bip32.ts` uses `mnemonic.isValid` method.
`docs/examples/accounts/bip39.ts` uses `mnemonic.isValid` method,
* Node.js Version: v21.6.2
> refactor: #666: pure and secure packages/core/src/mnemonic/mnemonic.ts

- README.md
The file `tsconfig.json` in the root directory of a **Next.js** project needs to include the following options.
```json
{
"compilerOptions": {
"target": "es2020",
"types": [
"@testing-library/jest-dom"
]
}
}
```
The file `README.md` introduces the **Troubleshooting - Next.js** section to explain how to configute **Next.js** effectively.
* Node.js Version: v21.6.2
> docs: 841 SDK core import with NextJS

- apps/sdk-nextjs-integration/next.config.mjs
- apps/sdk-nextjs-integration/package.json
- apps/sdk-nextjs-integration/yarn.lock
Import last released packages and improve next configuration.
> fix: improve nextjs app

- docs/examples/transactions/revert_reason.ts
- docs/templates/transactions.md
- docs/transactions.md
Examples for get revert reason
> feat: revert reason example

- apps/sdk-hardhat-integration/package.json
- apps/sdk-hardhat-integration/yarn.lock
- apps/sdk-nextjs-integration/yarn.lock
- apps/sdk-node-integration/yarn.lock
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_estimateGas/eth_estimateGas.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_estimateGas/fixture.ts
- yarn.lock
> feat: Improve eth_estimateGas and fix Dependencies of hardhat

- README.md
- docs/accounts.md
- docs/examples/accounts/keystore.ts
- packages/core/package.json
- packages/core/src/keystore/cryptography/ethers/const/index.ts
- packages/core/src/keystore/cryptography/ethers/const/keystore.ts
- packages/core/src/keystore/cryptography/ethers/index.ts
- packages/core/src/keystore/cryptography/ethers/keystore.ts
- packages/core/src/keystore/cryptography/experimental/index.ts
- packages/core/src/keystore/cryptography/experimental/keystore.ts
- packages/core/src/keystore/cryptography/index.ts
- packages/core/src/keystore/keystore.ts
- packages/core/src/keystore/types.d.ts
- packages/core/tests/keystore/keystore.unit.test.ts
- yarn.lock
Package is not che correct path.
This creates a problem of circle dependencies between core and the new package cryptography.
So for each experimental cryptography functionality e.g. keystore, we will add an 'experimental' and 'ethers' folder with experimental and ethers code.
> feat: experimental cryptography for keystore

- packages/core/.eslintrc.json
- packages/errors/.eslintrc.json
- packages/ethers-adapter/.eslintrc.json
- packages/hardhat-plugin/.eslintrc.json
- packages/logging/.eslintrc.json
- packages/network/.eslintrc.json
- packages/network/src/thor-client/logs/logs-module.ts
- packages/network/src/utils/vns/addresses.ts
- packages/network/src/utils/vns/index.ts
FIx imports on network module and add eslint support for this kind of warnings
> 905 bug fix  package import

- .changeset/funny-masks-cheat.md
- .changeset/pre.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-hardhat-integration/yarn.lock
- apps/sdk-nextjs-integration/package.json
- apps/sdk-nextjs-integration/yarn.lock
- apps/sdk-node-integration/package.json
- apps/sdk-node-integration/yarn.lock
- docs/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/network/tests/provider/rpc-mapper/methods/debug_traceTransaction/debug_traceTransaction.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_blockNumber/eth_blockNumber.testnet.test.ts
- packages/rpc-proxy/package.json
- yarn.lock
> feat: release

- apps/sdk-hardhat-integration/package.json
- apps/sdk-hardhat-integration/yarn.lock
- apps/sdk-nextjs-integration/package.json
- apps/sdk-nextjs-integration/yarn.lock
- apps/sdk-node-integration/package.json
- apps/sdk-node-integration/yarn.lock
- docs/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
- yarn.lock
> feat: release beta.11

- apps/sdk-hardhat-integration/package.json
- apps/sdk-hardhat-integration/yarn.lock
- apps/sdk-nextjs-integration/package.json
- apps/sdk-nextjs-integration/yarn.lock
- apps/sdk-node-integration/package.json
- apps/sdk-node-integration/yarn.lock
- docs/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/hardhat-plugin/src/index.ts
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
> Release 12

- docs/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
> Release 1.0.0-beta.13

- apps/sdk-hardhat-integration/package.json
- apps/sdk-hardhat-integration/yarn.lock
- apps/sdk-nextjs-integration/package.json
- apps/sdk-nextjs-integration/yarn.lock
- apps/sdk-node-integration/package.json
- apps/sdk-node-integration/yarn.lock
- packages/network/tests/thor-client/transactions/transactions.testnet.test.ts
> Post release 1.0.0-beta.13

- docs/package.json
- package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/README.md
- packages/rpc-proxy/package.json
- packages/rpc-proxy/src/index.ts
- packages/rpc-proxy/tsconfig.json
You can now run the RPC Proxy with a simple command!
> Improve RPC Proxy

- docs/examples/transactions/full-flow-delegator-private-key.ts
- docs/examples/transactions/full-flow-delegator-url.ts
- docs/examples/transactions/full-flow-no-delegator.ts
- docs/transactions.md
- packages/core/src/address/address.ts
- packages/network/src/provider/helpers/provider-internal-wallets/types.d.ts
- packages/network/src/thor-client/contracts/types.d.ts
- packages/network/tests/fixture.ts
- packages/network/tests/provider/providers/fixture.ts
This PR set the address type back to string
> refactor: set address type to string

- docs/contracts.md
- docs/examples/contracts/contract-event-filter.ts
- packages/network/src/thor-client/contracts/model/contract-filter.ts
- packages/network/src/thor-client/logs/logs-module.ts
- packages/network/tests/thor-client/contracts/contract.event.solo.test.ts
- packages/network/tests/thor-client/contracts/contract.event.testnet.test.ts
- packages/network/tests/thor-client/contracts/contract.solo.test.ts
- packages/network/tests/thor-client/contracts/fixture.ts
This PR organizes the results of contract event filtering into maps and arrays of EventLogs. The elements are grouped by topic hash, enabling users to work with specific sets of results efficiently.
> BREAKING CHANGES: Refactor Event Filtering and Grouping Mechanism

- packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
- packages/network/src/thor-client/transactions/transactions-module.ts
- yarn.lock
This PR imports ethers from the vechain core library in the network package
> Fix ethers import

- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_getBlockByNumber/eth_getBlockByNumber.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getBlockByHash/eth_getBlockByHash.mock.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getBlockByNumber/fixture.ts
Respect hydrated flag into eth_getBlockByNumber and eth_getBlockByHash
> fix: eth_getBlockByNumber and eth_getBlockByHash

- packages/network/src/provider/utils/formatter/logs/formatter.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_getLogs/eth_getLogs.ts
- packages/network/src/thor-client/logs/logs-module.ts
- packages/network/tests/provider/providers/ethers/ethers-provider.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getLogs/eth_getLogs.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getLogs/fixture.ts
- packages/network/tests/thor-client/transactions/transactions.testnet.test.ts
- packages/network/tests/utils/subscriptions/subscriptions.testnet.test.ts
This PR adds the support to an array of topics as input parameters to the method eth_getLogs
> feat: eth_getLogs input as an array of an array of topics

- packages/core/tests/address/address.unit.test.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_getBlockReceipts/eth_getBlockReceipts.ts
- packages/network/src/provider/utils/rpc-mapper/rpc-mapper.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getBlockReceipts/eth_getBlockReceipts.mock.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getBlockReceipts/eth_getBlockReceipts.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_getBlockReceipts/fixture.ts
Implement eth_getBlockReceipts
> feat: implement eth_getBlockReceipts for rpc provider

- packages/network/src/signer/signers/vechain-abstract-signer/vechain-abstract-signer.ts
- packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.solo.test.ts
this PR allows fixes the setting of the gas in transaction sending
> fix: set custom gas in transaction sending

- docs/diagrams/architecture/vcdm.md
- packages/core/src/vcdm/VeChainDataModel.ts
- packages/core/src/vcdm/index.ts
The package `packages/core/src/vcdm` introduces the **VeChain Data Model**.
* Node.js Version: 20.14.0
* Yarn Version: v1.22.22
> 1103-interface-vechaindatamodel

- packages/network/tests/provider/rpc-mapper/methods/eth_gasPrice/eth_gasPrice.mainnet.test.ts
Reproduce and solve the issue if present.
In meantime a main net test is added and it seems to work fine @victhorbi
> fix. understand problem of eth_gaPrice on mainnet

- apps/sdk-nextjs-integration/__tests__/hash-page.unit.test.tsx
- apps/sdk-nextjs-integration/__tests__/transfer-logs.unit.test.tsx
- apps/sdk-nextjs-integration/src/components/header/header.tsx
Improve tests for the nextJs sample app.
> Improve tests for apps/sdk-nextjs-integration

- .github/workflows/unit-integration-test.yml
workflow_run trigger
- manually
> chore: change workflow

- packages/rpc-proxy/src/index.ts
- packages/rpc-proxy/src/utils/args-validator/args-validator-and-getter.ts
- packages/rpc-proxy/src/utils/args-validator/args-validator.ts
- packages/rpc-proxy/src/utils/args/args-options.ts
- packages/rpc-proxy/src/utils/args/args-parser.ts
- packages/rpc-proxy/src/utils/config-validator/config-validator.ts
- packages/rpc-proxy/tests/utils/args/args-options.unit.test.ts
- packages/rpc-proxy/tests/utils/args/args-parser.unit.test.ts
Account and delegation fields into cli args with validation
> feat: add accounts and delegation flags

- packages/network/src/provider/utils/const/rpc-mapper/rpc-methods.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/index.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/web3_sha3/index.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/web3_sha3/web3_sha3.ts
- packages/network/src/provider/utils/rpc-mapper/rpc-mapper.ts
- packages/network/tests/provider/rpc-mapper/methods/engine_getPayloadV3/engine_getPayloadV3.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/web3_sha3/web3_sha3.testnet.test.ts
implement web3_sha3 rpc method.
> feat: web3_sha3 RPC Method

- docs/diagrams/architecture/vcdm.md
- packages/core/src/encoding/rlp/helpers/numerickind.ts
- packages/core/src/hdkey/HDKey.ts
- packages/core/src/utils/const/data.ts
- packages/core/src/utils/data/data.ts
- packages/core/src/vcdm/FPN.ts
- packages/core/tests/vcdm/FPN.unit.test.ts
The `FPN` class unifies the functions to check if textual expressions are signed/unsigned strictly positive or positive/negative integers.
* Node.js Version: v20.14.0
> refactor: 1218 FPN unifies integers validation

- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/net_listening/net_listening.ts
- packages/network/src/provider/utils/rpc-mapper/methods-map/methods/net_peerCount/net_peerCount.ts
- packages/network/src/provider/utils/rpc-mapper/rpc-mapper.ts
- packages/network/tests/provider/rpc-mapper/methods/net_listening/net_listening.mock.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/net_listening/net_listening.testnet.test.ts
- packages/network/tests/provider/rpc-mapper/methods/net_peerCount/net_peerCount.mock.testnet.test.ts
> feat: net listening rpc method

- packages/rpc-proxy/src/index.ts
- packages/rpc-proxy/src/types.d.ts
Add batch requests support for proxy
> feat: 1358 rpc request in batch implementation

- packages/network/src/thor-client/accounts/accounts-module.ts
- packages/network/src/thor-client/accounts/types.d.ts
- packages/network/tests/thor-client/accounts/accounts.solo.test.ts
The code renames as `AccountData` the interface `AccountDetail` at `packages/network/src/thor-client/accounts/types.d.ts` to allow the class `AccounDetail` in `packages/network/src/thor-client/accounts/accounts-module.ts` to implements the `AccountData` interface exposing the
additional computed properties:
* `vet` returning the account balance as a`VET` object,
* `vtho` returning the account energy balance as a `VTHO` object.
This solution preserves backward compatibility with the existing code.
* Node.js Version: v22.8.0
> 998  (no-breaking changes) get account  utility functions

- packages/core/tests/certificate/Certificate.unit.test.ts
Resume the lost code performing the unit tests of the `Certificate` class.
* Node.js Version: v22.8.0
> chore: 1386 Certificate unit tests resumed

- packages/core/src/certificate/Certificate.ts
- packages/network/src/signer/signers/vechain-abstract-signer/vechain-abstract-signer.ts
- packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
- packages/network/src/thor-client/debug/debug-module.ts
- packages/network/src/thor-client/transactions/transactions-module.ts
- packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.unit.test.ts
- packages/rpc-proxy/src/index.ts
- packages/rpc-proxy/src/utils/config-validator/config-validator.ts
This PR addresses the low security hotspot and the reliability issues raised by Sonar [here](https://sonarcloud.io/summary/overall?id=vechain_vechain-sdk).
Also fixes some straightforward smells.
Tested with the SDK suite
> fix: sonar low security spot, reliability issues and some smells

- .github/workflows/gitleaks.yml
- .gitleaksignore
- README.md
Introduces the GitHub Action for `gitleaks` to [prevent leaking secrets](https://github.com/gitleaks/gitleaks) in our commits to `main`.
Also removed `bash` tag from the README that was not required.
Via GitHub Actions.
> chore: `gitleaks` GitHub Action

- tsup.config.ts
tusp config with options for minify and treeshake
- manual build and run
> feat: added treeshake config

- .changeset/funny-masks-cheat.md
- .changeset/pre.json
- .github/workflows/publish-sdk.yml
- .github/workflows/rpc-proxy-vulnerability-scan.yml
- .github/workflows/unit-integration-test.yml
- docs/README.md
This PR added some missing references to packages across the monorepo.
Especially important the part that publishes `aws-kms-adapter`.
SDK test suite.
> chore: added missing references to packages

- packages/aws-kms-adapter/package.json
Title is self-explanatory.
SDK test suite
> chore: added missing attributes to `aws-kms-adapter`'s `package.json`

- .changeset/pre.json
- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- docs/package.json
- package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
- scripts/pre-release.ts
> fix: release candidate 1.0.0-rc.1

- packages/ethers-adapter/src/adapters/factory-adapter.ts
Fixes [this Sonar smell](https://sonarcloud.io/project/issues?severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&types=BUG&id=vechain_vechain-sdk&open=AZMKyau8-YFiw7lqi5G7&tab=code).
SDK test suite
* Node.js Version: 20.18.0
> fix: proper instantiation in `ethers-adapter`' `factoryAdapter`

- .changeset/config.json
- .changeset/pre.json
- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- apps/sdk-vite-integration/package.json
- docs/package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
PR with the version updated.
SDK test suite
* Node.js Version: 20.18.0
> chore: release 1.0.0-rc.2

- .github/workflows/build-lint.yml
- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- apps/sdk-vite-integration/package.json
- docs/package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
Also re-enables the check for circular dependencies.
SDK test suite
* Node.js Version: 20.18.0
> chore: release 1.0.0-rc.3

- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- apps/sdk-vite-integration/package.json
- docs/package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
> Release 1.0.0-rc.4

- packages/network/src/signer/signers/types.d.ts
- packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
- packages/network/src/thor-client/contracts/types.d.ts
- packages/network/src/thor-client/transactions/transactions-module.ts
- packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.testnet.test.ts
- packages/network/tests/thor-client/contracts/contract.erc20.testnet.test.ts
---------
Back-port of issue: #1593
Fixes #1593
> [TransactionRequestInput] - add fields (#1562)

- docs/diagrams/architecture/transaction.md
- docs/examples/thor-client/delegated-transactions.ts
- docs/examples/transactions/fee-delegation.ts
- docs/examples/transactions/full-flow-delegator-private-key.ts
- docs/thor-client.md
- docs/transactions.md
- packages/core/src/transaction/Transaction.ts
- packages/core/tests/transaction/Transaction.unit.test.ts
- packages/core/tests/vcdm/Address.unit.test.ts
- packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
- packages/network/tests/thor-client/transactions/transactions-thorest.solo.test.ts
Backport #1595 to 1.0.0 branch
Fixes #1595 
> Backport 1595 to 1.0.0

- apps/sdk-nextjs-integration/package.json
- apps/sdk-nextjs-integration/src/app/transfer-logs/page.tsx
- packages/core/tests/vcdm/Address.unit.test.ts
- packages/rpc-proxy/package.json
- yarn.lock
Update dependencies that `yarn audit` flagged as moderate or higher priority
Fixes security warnings
> chore: update dependencies

- packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
Update fucntion documentation
Fixes #1657 
> chore: update function doc

- packages/core/src/vcdm/Address.ts
Fix error message
Fixes #1659 
> chore: error message

- packages/core/jest.config.js
- packages/core/src/hdkey/HDKey.ts
- packages/core/tests/hdkey/HDKey.unit.test.ts
Update BIP32 derivation path validation to use regex instead
Fixes #1727 
* Node.js Version:18.18.0
> chore: bip32 derivation path - validationupdate

- packages/thorest/src/thor/logs/EventLogsResponse.ts
- packages/thorest/src/thor/logs/FilterOptions.ts
- packages/thorest/src/thor/logs/FilterRange.ts
- packages/thorest/src/thor/logs/LogMeta.ts
- packages/thorest/src/thor/logs/QueryVETTransferEvents.ts
- packages/thorest/src/thor/logs/TransferLogsResponse.ts
- packages/thorest/tests/thor/logs/QuerySmartContractEvents.unit.test.ts
- packages/thorest/tests/thor/logs/QueryVETTransferEvents.unit.test.ts
Reviewed, added tests, added missing fields and added comments to the thor/log package
Fixes #1720 
> 1720 new net code review and test    thorlog package

- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- apps/sdk-vite-integration/package.json
- docs/package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
> chore: 1.0.0

- packages/thorest/tests/ws/MozillaWebSocketClient.unit.test.ts
- packages/thorest/tests/ws/WebSocketClient.unit.test.ts
Reviewed thorest/ws and added unit tests
Fixes # 1716
Unit tests
> feat: added unit tests for thorest/ws package

- apps/sdk-hardhat-integration/hardhat.config.ts
- packages/core/src/transaction/Clause.ts
- packages/core/src/vcdm/currency/Token.ts
- packages/core/src/vcdm/currency/index.ts
- packages/core/tests/transaction/Clause.unit.test.ts
- packages/core/tests/vcdm/currency/Token.unit.test.ts
Adds a base class to model Tokens with different decimal precisions
Adds a clause builder to transfer tokens
> Token class and Transfer Token Clause

- packages/network/src/http/SimpleHttpClient.ts
- packages/network/src/thor-client/transactions/helpers/delegation-handler.ts
- Fix fee delegation handler http post to have correct content-type header
- Fix url in error message to be valid url
> fix: delegation handler and error url

- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- apps/sdk-vite-integration/package.json
- docs/package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/rpc-proxy/package.json
Increment package numbers for 1.1.0 release
> release 1.1.0

- .github/workflows/rpc-proxy-docker.yml
Quick fix to rpc release workflow to allow manual release
> chore: fix rpc docker wf to run manually

- packages/thorest/src/thor/accounts/GetAccountResponse.ts
- packages/thorest/tests/thor/accounts/InspectClauses.unit.test.ts
- packages/thorest/tests/thor/accounts/RetrieveAccountDetails.unit.test.ts
- packages/thorest/tests/thor/accounts/RetrieveContractBytecode.unit.test.ts
- packages/thorest/tests/thor/accounts/RetrieveStoragePositionValue.unit.test.ts
Reviewed thor/account package and added unit tests
Fixes #1717 
> 1717 new net p1 code review and test    thoraccount package

- packages/thorest/src/http/FetchHttpClient.ts
- packages/thorest/src/http/index.ts
- packages/thorest/tests/http/FetchHttpClient.testnet.test.ts
- packages/thorest/tests/http/FetchHttpClient.unit.test.ts
- yarn.lock
Added unit tests, added support for dependency injections for HttpClient so that it is easier to test and allow for custom implementations. 
Fixes #1715
> feat: added unit tests and allowed dependency injection for FetchHttpClient

- packages/thorest/src/thor/debug/PostDebugTracerCallRequest.ts
- packages/thorest/src/thor/debug/TargetPath.ts
- packages/thorest/tests/thor/debug/RetrieveStorageRange.unit.test.ts
- packages/thorest/tests/thor/debug/StorageRange.unit.test.ts
- packages/thorest/tests/thor/debug/TargetPath.unit.test.ts
- packages/thorest/tests/thor/debug/TraceCall.unit.test.ts
- packages/thorest/tests/thor/debug/TraceTransactionClause.unit.test.ts
- packages/thorest/tests/thor/debug/TracerName.unit.test.ts
Added unit tests, a new class for the `target` field and upgraded type checking for ProvedWork
Fixes #1719
> 1719 new net p1 code review and test    thordebug package

- packages/network/src/provider/utils/rpc-mapper/methods/eth_feeHistory/eth_feeHistory.ts
- packages/network/src/provider/utils/rpc-mapper/methods/eth_maxPriorityFeePerGas/eth_maxPriorityFeePerGas.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_feeHistory/eth_feeHistory.mock.test.ts
- packages/network/tests/provider/rpc-mapper/methods/eth_maxPriorityFeePerGas/eth_maxPriorityFeePerGas.mock.test.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> 2056 galactica methods check if hardfork happened

- package.json
Update to workspace command
Fixes #2101
Minor change
> chore: updated solo setup workspace commands

- packages/network/src/provider/utils/rpc-mapper/methods/eth_gasPrice/eth_gasPrice.ts
- packages/network/src/thor-client/contracts/contracts-module.ts
- packages/network/src/thor-client/transactions/transactions-module.ts
- packages/network/tests/thor-client/contracts/contract.solo.test.ts
- packages/network/tests/thor-client/contracts/contract.testnet.test.ts
Rename `getBaseGasPrice` to `getLegacyBaseGasPrice`.
No tests needed, only unit tests and linters to pass.
* Node.js Version: v20.11.0
> 2100 feat(contract): rename getBaseGasPrice to getLegacyBaseGasPrice

- apps/sdk-cloudflare-integration/package.json
- apps/sdk-hardhat-integration/package.json
- apps/sdk-nextjs-integration/package.json
- apps/sdk-node-integration/package.json
- apps/sdk-vite-integration/package.json
- docs/package.json
- packages/aws-kms-adapter/package.json
- packages/core/package.json
- packages/errors/package.json
- packages/ethers-adapter/package.json
- packages/hardhat-plugin/package.json
- packages/logging/package.json
- packages/network/package.json
- packages/solo-setup/package.json
> build: 1.2.0-rc.3

- packages/thorest/src/thor/fork/forkDetector.ts
- packages/thorest/src/thor/fork/index.ts
- packages/thorest/tests/thor/fork/ForkDetector.solo.test.ts
- packages/thorest/tests/thor/fork/ForkDetector.unit.test.ts
Ported the fork detector code to V2. Added solo and unit tests.
Fixes #2041
Unit & Solo
> 2041 sdk v2   packagesnetworksrcthor clientfork porting

- packages/sdk/src/hdkey/HDKey.ts
- packages/sdk/tests/hdkey/HDKey.unit.test.ts
The method `packages/sdk/src/hdkey/HDKey.ts!fromMnemonic(words: string[], path: string = this.VET_DERIVATION_PATH, passphrase?: string): HDKey` receipts the suggestion published at  https://skynet.certik.com/projects/vechain?auditId=Vechain%20SDK%20&findingId=HDK-02#code-security.
Fixes #1885
* Node.js Version: v24.0.0
> fix: 1885 HDK-02

- .github/workflows/on-pr.yml
- packages/sdk/eslint.config.mjs
- packages/sdk/package.json
- packages/sdk/src/clients/PublicClient.ts
- packages/sdk/src/clients/WalletClient.ts
Fix `yarn lint` command, and fix linting issues
Re-enabled linting as part of PR checks
Fixes #2270 
> fix: linting

- packages/sdk/src/http/CookieStore.ts
- packages/sdk/src/http/FetchHttpClient.ts
- packages/sdk/src/http/HttpClient.ts
- packages/sdk/src/http/HttpOptions.ts
- packages/sdk/src/thor/accounts/methods/RetrieveAccountDetails.ts
- packages/sdk/tests/http/FetchHttpClient.unit.test.ts
Added http options:
- timeout
- store cookies
- custom headers
to FetchHttpClient
Fixes #2269 
> feature: http options

- packages/sdk/jest.config.js
- packages/sdk/src/clients/Contract.ts
- packages/sdk/src/clients/WalletClient.ts
- packages/sdk/src/clients/index.ts
- packages/sdk/src/core.ts
- packages/sdk/test-contract.ts
- packages/sdk/tests/clients/Contract.unit.test.ts
Added the getContractInstance from viem.
Fixes # getContrctIntance
* Node.js Version: 22
* Yarn Version: 1.2
> feat: added get contract

- packages/sdk/src/clients/WalletClient.ts
- packages/sdk/tests/clients/publicClient/blocks.solo.test.ts
Standardized the params accross viem clients
> feat: standard params

- packages/sdk/src/thor/thorest/subscriptions/response/SubscriptionBlockResponse.ts
- packages/sdk/src/thor/thorest/subscriptions/response/SubscriptionBlockResponseJSON.ts
- packages/sdk/tests/thor/thorest/subscriptions/BeatsSubscription.unit.test.ts
- packages/sdk/tests/thor/thorest/subscriptions/BlocksSubscription.baseFeePerGas.solo.test.ts
- packages/sdk/tests/thor/thorest/subscriptions/BlocksSubscription.unit.test.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix: add baseFeePerGas field and fix tests
