packages/rpc-proxy/README.md, packages/rpc-proxy/package.json, packages/rpc-proxy/src/index.ts
Add logging to RPC proxy in order to improve usability
=> feat; add logging system for rpc proxy

packages/provider/tests/rpc-mapper/methods/eth_getLogs/eth_getLogs.mock.solo.test.ts, packages/provider/tests/rpc-mapper/methods/eth_getLogs/eth_getLogs.testnet.test.ts, packages/provider/tests/rpc-mapper/methods/eth_getLogs/fixture.ts
Probably last solutions for eth_getLogs test failing.
=> fix: mock some tests and minimize logs call

packages/provider/src/utils/formatter/transactions/formatter.ts, packages/provider/tests/rpc-mapper/methods/eth_getTransactionReceipt/fixture.ts
Fixing the issue that using the RPC Proxy the function eth_getTransactionReceipt will only return logs of the first clause of a transaction.
The method formatTransactionReceiptToRPCStandard() was limiting the results to the first clause (outputs[0]), instead a correct receipt should return all events of a transaction.
=> Fix formatTransactionReceiptToRPCStandard()

packages/network/src/utils/poll/event.ts, packages/network/tests/utils/poll/event/event-poll.unit.test.ts
In the packages/network/src/utils/poll/event.ts the class `EventPoll` has a new private readonly `hasToStopOnError`: boolean; property to flag the _intervalLoop() if to stop in the case an error is caught.
If an error stop the poll, the code called by the onError call back can resume it calling startListen or making a new EventLoop.
* Node.js Version: 22.6.2
* Yarn Version: v1.22.21
=> 495 thor client  option to not stop listening on interval error

package.json, packages/core/src/hdnode/hdnode.ts, packages/core/src/mnemonic/mnemonic.ts, packages/core/tests/hdnode/hdnode.unit.test.ts, packages/errors/src/utils/assert/assert.ts, packages/errors/src/utils/error-builder/error-builder.ts, packages/errors/src/utils/error-builder/provider-error-builder.ts, packages/errors/src/utils/error-message-builder/error-message-builder.ts
The code at 
- packages/core/src/hdnode/hdnode.ts
- packages/core/src/mnemonic/mnemonic.ts
use mnemonic words and private keys as functions' parameters. In case of exception mnemonic words could be leaked by called methods of internal libraries [BIP-32](https://github.com/paulmillr/scure-bip32) and [BIP-39](https://github.com/paulmillr/scure-bip39), albeit in the actual release of these libraries shadow sensitive data.
**The proposed code assures no sensitive data such as mnemonic words or private keys are leaked because error thrown.**
The code at 
- packages/errors/src/utils/assert/assert.ts
- packages/errors/src/utils/error-builder/error-builder.ts
- packages/errors/src/utils/error-builder/provider-error-builder.ts
- packages/errors/src/utils/error-message-builder/error-message-builder. …
=> refactor: #666:  mnemonic improvements

packages/rpc-proxy/src/index.ts, packages/rpc-proxy/src/types.d.ts
Same account format of hardhat:
```
"accounts": {
"mnemonic": "...",
"count": ...
}
```
AND
```
"accounts": [...]
```
=> feat: more account formats for proxy

packages/core/src/address/address.ts, packages/core/src/clause/clause.ts
This tiny PR makes the code at `packages/core/src/clause/clause.ts` to depends on internal `addressUtils.isAddress` function instead of `ethers.isAddress`.
* Node.js Version: v21.6.2
=> refactor: 666 pure and secure `packages/core/src/clause.ts`

docs/contracts.md, docs/examples/contracts/contract-create-ERC20-token.ts, docs/examples/contracts/contract-delegation-ERC20.ts, docs/templates/contracts.md
This PR adds the documentation for a read transaction with multiple clauses
=> docs: multiple clauses read

packages/network/tests/provider/rpc-mapper/methods/eth_sendTransaction/eth_sendTransaction.solo.test.ts
Test **eth_sendTransaction - Should be able to send a transaction with value undefined** at `packages/network/tests/provider/rpc-mapper/methods/eth_sendTransaction/eth_sendTransaction.solo.test.ts` uses the accounts
- from = 0xabef6032b9176c186f6bf984f548bda53349f70a aka ALL_ACCOUNTS[18]
- to = 0x865306084235bf804c8bba8a8d56890940ca8f0b aka ALL_ACCOUNTS[19];
not used in any other test.
Fixes # 897
- https://github.com/vechain/vechain-sdk-js/issues/897
* Node.js Version: v22.2.0
=> fix: 897 test race condition

packages/core/src/bloom/bloom.ts, packages/core/tests/bloom/bloom.unit.test.ts, yarn.lock
Bloom filters are composable if they share `m` and `k` parameters.
* Node.js Version: v22.2.0
=> feat: 802 composable bloom filters

packages/core/src/utils/units/units.ts, packages/core/tests/utils/units/units.unit.test.ts
The code fixes a bug in the function `unitsUtils.parseUnits` in the file packages/core/src/utils/units/units.ts leading to include non meaningful digits in BigNumber conversion to `string` to be parsed as `bigint`.
New tests are introduced to compare `ethers` behaviour with the drop-in functions provided by `unitUtils`, the latter are based on `bignumber.js` library.
The `bignumberjs` library configures its setting - specifically about the fixed digits precision and rounding methods - globally: this means if some code using this SDK needs to change `BigNumber` settings, the behaviour of `unitUtils` functions is altered in a potentially incorrect way. 
This code stores the configuration of `BigNumber`, at the beginning of the execution of the format/parse functions, set it as needed to …
=> 928 bug parseunits throws on numbers below 01

packages/core/src/assertions/keystore/keystore.ts, packages/core/src/assertions/transaction/transaction.ts, packages/core/src/secp256k1/secp256k1.ts
The re-introduction of previous code to implenemnt tyhe keystore, based on `ethers` reintroduced the sensitive information leak.
* Node.js Version: v20.14.0
=> fix: 666 no pk leak in errors

packages/network/jest.config.browser.js, packages/network/tests/test-utils.ts
We now test all our code on browser env without exceptions.
=> Remove test path ignore patterns

packages/core/package.json, packages/errors/package.json, packages/ethers-adapter/package.json, packages/hardhat-plugin/package.json, packages/logging/package.json, packages/network/package.json, packages/rpc-proxy/package.json
Fix NPM packages. Makes them compatible with CJS + ESM
=> fix: npm publishing compatability

docs/accounts.md, docs/address.md, docs/diagrams/architecture/vcdm.md, docs/examples/accounts/pubkey.ts, docs/examples/address/address-derivation.ts, docs/examples/address/address-validation.ts, packages/core/src/vcdm/Address.ts
Class `packages/core/src/vcdm/Address.ts` documented with security audit remarks.
UML diagram at `docs/diagrams/architecture/vcdm.md` includes full Address functionalities.
Documentation's examples reworked to use the Address and *VeChain Data Model* types when possible. 
* Node.js Version: v20.14.0
=> feat: 1105 class Address.ts documented in examples and diagrams

apps/sdk-nextjs-integration/src/app/hash/page.tsx, packages/core/src/hash/Blake2b256.ts, packages/core/src/hash/Keccak256.ts, packages/core/src/hash/Sha256.ts, packages/core/tests/hash/Blake2b256.unit.test.ts, packages/core/tests/hash/Keccak256.unit.test.ts, packages/core/tests/hash/Sha256.unit.test.ts
It adds the overload of the hash functions that was in place before the OOP approach was introduced to keep backwards compatibility.
Using the unit tests + the NextJS sample app
* Node.js Version: 20.12.1
=> fix(hash functions): backwards compatibility overload

.github/workflows/sonar.yml, .github/workflows/unit-integration-test.yml
Fix artifact download (hopefully)
- manually
=> chore: fix download artifact

packages/errors/tests/helpers/helpers.unit.test.ts, packages/network/src/signer/signers/types.d.ts, packages/network/src/signer/signers/vechain-abstract-signer/vechain-abstract-signer.ts, packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts, packages/rpc-proxy/README.md, packages/rpc-proxy/src/index.ts, packages/rpc-proxy/src/utils/args/args-options.ts
Documented CLI proxy command line args
=> feat: roc proxy cli args documentation

packages/network/src/provider/utils/const/rpc-mapper/rpc-methods.ts, packages/network/src/provider/utils/rpc-mapper/methods-map/methods/net_peerCount/net_peerCount.ts, packages/network/src/provider/utils/rpc-mapper/rpc-mapper.ts, packages/network/src/thor-client/nodes/nodes-module.ts, packages/network/tests/provider/rpc-mapper/methods/net_peerCount/net_peerCount.mock.testnet.test.ts, packages/network/tests/provider/rpc-mapper/methods/net_peerCount/net_peerCount.testnet.test.ts
Implement neet_peerCount RPC method
=> feat: neet_peerCount RPC Method 

packages/core/src/vcdm/abi/ABIEvent.ts, packages/core/src/vcdm/abi/ABIFunction.ts, packages/core/src/vcdm/abi/ABIItem.ts
Since we have just `AbiFunction` and `AbiEvent`, it is more accurate to use the implementation of this PR so we avoid casts to `unknown`.
Test suite of the repo
=> fix: using correct types for `viem` ABI

packages/rpc-proxy/Dockerfile
There was no build phase on the Dockerfile so I added one. The final image should only contain the files that are needed to run the application and not all of the source files and other unnecessary files.
This is a non functional change. Ensure the dockerfile builds and runs.
=> 1312 2 phase build for the rpc proxy dockerfile

packages/rpc-proxy/Dockerfile
The pipeline is currently broken since the docker image for `rpc-proxy` [would be executed by root](https://sonarcloud.io/project/security_hotspots?id=vechain_vechain-sdk&branch=main&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true). This PR adds an user to solve that.
With the test suite.
=> fix(`rpc-proxy`): Docker should not run with root

packages/core/src/vcdm/abi/ABIContract.ts, packages/core/src/vcdm/abi/ABIEvent.ts, packages/core/src/vcdm/abi/ABIFunction.ts, packages/core/tests/abi/abi.unit.test.ts, packages/network/src/thor-client/contracts/contracts-module.ts, packages/network/src/thor-client/contracts/types.d.ts, packages/network/src/thor-client/logs/logs-module.ts, packages/network/src/thor-client/logs/types.d.ts, packages/network/tests/thor-client/contracts/contract.erc721.solo.test.ts, packages/network/tests/thor-client/contracts/contract.event.mainnet.test.ts
Removed `ethers.Result` dependency. Its main feature (parameter ordering) is also included by default in `viem`.
`ethers` methods converted into methods returning an array of values, so the user can decide between this or the standard `viem` output (object describing the parameters with their values).
Reusing the test suite of the SDK.
=> refactor: `ethers.Result` dependency removed from encode/decode ABI items

packages/core/src/transaction/Transaction.ts, packages/core/tests/transaction/Transaction.unit.test.ts
The class `packages/core/src/transaction/Transaction.ts` uses `bigint` type instead of `number` to compute gas.  The use of `bigint` avoids approximation due to the chain of sums of products of big numbers since gas values are at least 18 decimal digits long.
Internal enhancement only.
* Node.js Version: v22.8.0
=> refactor: 1361 gas math in bigint

packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/type-extensions.ts, packages/hardhat-plugin/tests/eth_getTransactionCount-default-value-project.unit.test.ts, packages/hardhat-plugin/tests/eth_getTransactionCount-no-value-project.unit.test.ts, packages/hardhat-plugin/tests/eth_getTransactionCount-random-value-project.unit.test.ts, packages/hardhat-plugin/tests/hardhat-mock-projects/eth_getTransactionCount-default-value-project/hardhat.config.ts, packages/hardhat-plugin/tests/hardhat-mock-projects/eth_getTransactionCount-no-value-project/hardhat.config.ts, packages/hardhat-plugin/tests/hardhat-mock-projects/eth_getTransactionCount-random-value-project/hardhat.config.ts, packages/network/src/provider/providers/hardhat-provider/hardhat-provider.ts, packages/network/tests/provider/providers/hardhat/hardhat-provider.testnet.test.ts
Add the capability to choose wether we can return 0x0 or a random number for eth_getTransactionCount RPC endpoint
=> feat: eth_getTransactionCount can return 0x0 const if configured

docs/diagrams/architecture/transaction.md, packages/core/src/transaction/Transaction.ts, packages/core/tests/transaction/Transaction.unit.test.ts, packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
`getSignatureHash` renamed to `getTransactionHash` because of the reason in the title.
Tested with the SDK suite
=> refactor: `getSignatureHash` renamed to `getTransactionHash` since that is what we are hashing

docs/diagrams/architecture/vcdm.md, packages/core/src/vcdm/FixedPointNumber.ts, packages/core/tests/vcdm/FixedPointNumber.unit.test.ts
The `FixedPointNumber` class showed a divergent limit from the theoretic real result of an exponentiation operation
with a relative big exponent.
The [Exponentiation by Squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring) algorithm was fixed
and verified in specific tests using the [Compound Interest](https://en.wikipedia.org/wiki/Compound_interest) 
algorithm as challenge.
Fixes #1439
* Node.js Version: v22.8.0
=> 1439  bug   FixedPointNumber class power function

.gitleaksignore, docker-compose.localstack.yml, localstack/init/kms.sh, packages/aws-kms-adapter/README.md, packages/aws-kms-adapter/package.json, packages/aws-kms-adapter/src/KMSVeChainProvider.ts, packages/aws-kms-adapter/src/KMSVeChainSigner.ts, packages/aws-kms-adapter/src/index.ts, packages/aws-kms-adapter/tests/KMSVeChainProvider.unit.test.ts, packages/aws-kms-adapter/tests/KMSVeChainSigner.solo.test.ts, packages/aws-kms-adapter/tests/KMSVeChainSigner.testnet.test.ts, packages/aws-kms-adapter/tests/KMSVeChainSigner.unit.test.ts, packages/aws-kms-adapter/tests/fixture.ts, packages/aws-kms-adapter/tests/test-aws-credentials.json, packages/network/src/provider/providers/vechain-provider/vechain-provider.ts, packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts, packages/network/tests/provider/providers/vechain/vechain-provider.testnet.test.ts
This PR extends the usage of AWS KMS for delegation.
Closes #1413 .
Using the existing test suite + new tests have created to target testnet for delegation url.
=> feat: AWS KMS for delegation

docs/contracts.md, docs/examples/contracts/contract-create-ERC20-token.ts, docs/examples/evm-extension/evm-extension.ts, packages/errors/src/available-errors/contract/contract.ts, packages/network/src/provider/utils/rpc-mapper/methods/eth_gasPrice/eth_gasPrice.ts, packages/network/src/thor-client/contracts/contracts-module.ts, packages/network/src/thor-client/contracts/model/contract-proxy.ts, packages/network/src/thor-client/contracts/types.d.ts, packages/network/src/utils/vns/index.ts, packages/network/tests/thor-client/contracts/contract.erc20.solo.test.ts, packages/network/tests/thor-client/contracts/contract.solo.test.ts, packages/network/tests/thor-client/contracts/contract.testnet.test.ts, packages/network/tests/thor-client/contracts/fixture.ts
Refactor of the `ContractCallResult` type so includes an error message. This way the `executeCall` methods return a single type rather than 2.
`plain` value vs `array` value applies mainly to structs, so for the following contract method, the result would be:
```
// Custom struct type
struct ExampleStruct {
uint id;
string name;
}
function structData(ExampleStruct memory _structData) public pure returns (ExampleStruct memory) {
return _structData;
}
```
- `plain`: { id: 10n, name: 'test' }
- `array`: [[10n, 'test']] (structs are represented as nested arrays of values, tuple types would be a flattened array of values)
Closes #1438 
Using the existing SDK codebase
=> refactor(`ContractCallResult`): Added `errorMessage`, `plain` value and `success` flag

docs/templates/thor-client.md, docs/thor-client.md, packages/network/src/provider/utils/rpc-mapper/methods/net_peerCount/net_peerCount.ts, packages/network/src/thor-client/nodes/nodes-module.ts
Closes #1486 
SDK test suite.
* Node.js Version: 20.18.0
=> refactor: returning connected peers after dealing with null

packages/network/src/provider/utils/rpc-mapper/methods/eth_getUncleByBlockHashAndIndex/eth_getUncleByBlockHashAndIndex.ts, packages/network/src/provider/utils/rpc-mapper/methods/eth_getUncleByBlockNumberAndIndex/eth_getUncleByBlockNumberAndIndex.ts, packages/network/src/provider/utils/rpc-mapper/rpc-mapper.ts, packages/network/tests/provider/rpc-mapper/methods/eth_getUncleByBlockHashAndIndex/eth_getUncleByBlockHashAndIndex.testnet.test.ts, packages/network/tests/provider/rpc-mapper/methods/eth_getUncleByBlockNumberAndIndex/eth_getUncleByBlockNumberAndIndex.testnet.test.ts, packages/rpc-proxy/tests/e2e_rpc_proxy.solo.test.ts
eth_getUncleByBlockNumberAndIndex
eth_getUncleByBlockHashAndIndex
were returning {} instead of null
Fixes #1518 
=> issue: 1518 - rpc proxy return value for get uncles by block hash/number by index

docs/diagrams/architecture/http.md, packages/network/src/http/SimpleHttpClient.ts, packages/network/tests/http/SimpleHttpClient.solo.test.ts, packages/network/tests/thor-client/ThorClient.unit.test.ts
The class `packages/network/src/http/SimpleHttpClient.ts` introduces the possibility to sets headers in the `SimpleHttpClient` constructor.
The headers of built objects are included in every request made through the `http` method, if not overwritten by the `params` argument of the class  `packages/network/src/http/HttpParams.ts`.
This solutions allows to set headers to manage HTTP [cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) and [control-caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching).
See the test `'ok <- GET and validate` at `packages/network/tests/http/SimpleHttpClient.solo.test.ts`.
Fixes #1124 
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> 1124 request   restore ability to inject custom fetch instance

docs/diagrams/architecture/transaction.md, packages/core/src/transaction/Transaction.ts, packages/core/tests/transaction/Transaction.unit.test.ts
The class `Transaction` at `packages/errors/src/available-errors/transaction/transaction.ts` provides two additional methods:
- `signForDelegator(signerPrivateKey: Uint8Array): Transaction` prepares the transaction to be full signed calling
- `signAsDelegator(signer Address, delegatorPrivateKey: Uint8Array): Transaction` completes the signature.
The method `isSigned` returns
- `false`
- if the transaction is not signed;
- if the transaction is delegated and signed only with `signForDelegation` but not signed with `signAsDelegator` later;
- `true`
- if the transaction is not delegated and signed with `sign`;
- if the transaction is delegated
- signed with `signWithDelegator`;
- signed with `signForDelegator` and then with `signAsDelegator`.
Fixes #1545
Please delete options that are not …
=> 1545 request   split fee delegation in 2 separate methods

docs/examples/contracts/contract-usage.ts
Added example with contract interaction to our docs
Fixes # (#1550 )
- manually tested on thor solo docker node
=> feat: add example for interacting with contract

packages/core/src/transaction/Transaction.ts, packages/core/tests/transaction/Transaction.unit.test.ts
The `packages/core/src/transaction/Transaction.ts` class allows the making of incomplete signed delegated transaction.
This scenario happens between two delegator and delegates parties running JS in two different computers.
The first party sign the transactions and transmits the array of bytes representing the transaction to the second party.
The second party needs to build the transaction from a byte array and complete the signature process.
Fixes #1560 
* Node.js Version: v23.1.0
=> fix: 1560 Transaction.ts allows making of incomplete signed instances

packages/core/src/vcdm/HexUInt32.ts, packages/core/tests/vcdm/HexUInt32.unit.test.ts
Extent hexUint class to a class enforcing lenght (hexUint 32). Then extend in subclasses aiming to replace thorId with the new classes representing the new semantic (blockId vs txId vs ....)
=> refactor: create HexUInt32 class

docs/diagrams/v2/net/thor/blocks/blocks.md, docs/diagrams/v2/net/thor/transactions/transactions.md, packages/thorest/src/thor/blocks/ExpandedBlockResponse.ts, packages/thorest/src/thor/transactions/TxMeta.ts
Changing from using `bigint` to using VCDM's `UInt` for timestamps
Fixes #1842
Chore and doc update
Unit/integration tests passing
=> 1842 new net p1   change timestamps from using bigint to using uint

docs/diagrams/architecture/transaction.md, packages/core/src/transaction/Transaction.ts
Class `packages/core/src/transaction/Transaction.ts` renamed as `getTransactionHash(sender?: Address): Blake2b256` the argument previously named `gasPayer`.
Fixes #1873
* Node.js Version: v23.1.0
=> fix: 1873 `Transaction.getTransactionHash(sender)` rename

packages/core/src/transaction/Transaction.ts, packages/core/tests/transaction/Transaction.unit.test.ts
Allowing the use of signAsGasPayer with an unsigned transaction. In order to maintain backwards compatibility, for people using it with transactions that are signed by the sender, it returns the transaction with just the signature of the gas payer. Therefore, the resulting transaction object cannot be broadcasted right after, it needs to be manually rebuilt to contain both the sender and the gaspayer signature concatenated.
=> Allowing signasgaspayer on unsigned tx

docker-compose.rpc-proxy.yml, packages/network/src/provider/utils/const/chain-id/chain-id.ts, packages/network/src/provider/utils/rpc-mapper/methods/eth_chainId/eth_chainId.ts, packages/network/tests/provider/fixture.ts, packages/network/tests/provider/providers/fixture.ts, packages/network/tests/provider/rpc-mapper/methods/eth_chainId/eth_chainId.solo.test.ts, packages/network/tests/provider/rpc-mapper/methods/eth_getTransactionByBlockHashAndIndex/fixture.ts, packages/network/tests/provider/rpc-mapper/methods/eth_getTransactionByBlockNumberAndIndex/fixture.ts, packages/rpc-proxy/README.md, packages/rpc-proxy/tests/e2e_rpc_proxy.solo.test.ts, scripts/test-rpc-proxy.ts
Fixes the chain Id to return `0x186a9` for mainnet and `0x186aa` for testnet
For other networks (solo or some custom genesis) it returns the chain tag (last byte of the genesis block id)
Fixes: Integration issue feedback
=> fix: chainid

packages/core/src/vcdm/Gas.ts, packages/core/src/vcdm/index.ts, packages/thorest/src/thor/accounts/ExecuteCodesRequest.ts, packages/thorest/src/thor/accounts/ExecuteCodesResponse.ts, packages/thorest/src/thor/blocks/CommonBlockResponse.ts, packages/thorest/src/thor/debug/PostDebugTracerCallRequest.ts, packages/thorest/src/thor/subscriptions/SubscriptionBeat2Response.ts, packages/thorest/src/thor/subscriptions/SubscriptionBlockResponse.ts, packages/thorest/src/thor/transactions/GetTxResponse.ts, packages/thorest/src/thor/transactions/Receipt.ts
Added a specific class to handle gas and changed relevant gas parameters from VTHO to this new Gas class in thorest
It didn't break any tests in thorest
=> feat: created gas class

.github/workflows/publish-sdk.yml, .github/workflows/rpc-proxy-docker.yml, .github/workflows/rpc-proxy.yml, packages/rpc-proxy/README.md
- Change github workflow to release RPC proxy to docker manually
- Update Readme for RPC proxy
=> Update RPC Docs

packages/core/src/transaction/Clause.ts, packages/core/tests/transaction/Clause.unit.test.ts
The CallFunction clause builder would only accept a VET value > 0. This fixes an edge case where the clause can contain a zero value field.
Fixes #1757 
=> Fix - 1757

packages/core/tests/vcdm/Nonce.unit.test.ts
Creates unit tests for the `Nonce` class.
We are not using the `Nonce` class anywhere within our code. Is that fine for now? At the same time, we can see that under `TransactionBody`, the `nonce` field is either a `string` or a `number`.
Closes #2050 
Ran the tests using `npm run test`
* Node.js Version: v22.11.0
=> feat: add unit tests for Nonce class

packages/core/src/vcdm/FixedPointNumber.ts, packages/core/tests/vcdm/FixedPointNumber.unit.test.ts
The tests at `packages/core/tests/vcdm/FixedPointNumber.unit.test.ts` compares fixed point precision numbers with floating point precision numbers. Equality tests must admit a range of approximation since JS `number` type IEEE 754 approximate results of rational values.
Recent JS runtime changes (NodeJS v24) changed the approximation logic in string rendering, hence few tests didn't work anymore.
**The tests use https://jestjs.io/docs/expect#tobeclosetonumber-numdigits to unify the legitimate approximation logic.**
Fixes #2075
* Node.js Version: v24.0.0 …
=> 2075 bug   fix fixed point precision math tests

packages/core/src/transaction/Transaction.ts
Adding check for signature length on transaction object instantiation and separated the gas payer and transaction sender signatures logic from the transaction signature (being both concatenated, or just the sender signature if they are also the gas payer)
Fixes #1781
=> 1781 request   check for signature length on transaction object instantiation

packages/network/src/thor-client/blocks/types.d.ts, packages/network/tests/thor-client/blocks/blocks-dynamicFee.solo.test.ts, packages/network/tests/thor-client/blocks/fixture.ts, packages/network/tests/thor-client/transactions/fixture-thorest.ts
Fixes build for wrong type for transaction type
Fixes testnet tests
=> chore: fix build and tests

packages/network/src/thor-client/transactions/types.d.ts
The interface `TransactionSimulationResult` in `packages/network/src/thor-client/transactions/types.d.ts` exposed the property `events: Event` where the type referred to [DOM Event](https://developer.mozilla.org/en-US/docs/Web/API/Event), obviously not the [Thor Event](https://mainnet.vechain.org/doc/stoplight-ui/#/schemas/Event).
The fix introduces the `TransactionSimulationEvent` interface and changes property `events: TransactionSimulationEvent[]` of `TransactionSimulationResult` in `packages/network/src/thor-client/transactions/types.d.ts`.
Fixes #2116
**Test …
=> 2116 bug   simulatetransaction doesnt return what expected

packages/core/src/vcdm/FixedPointNumber.ts, packages/core/tests/vcdm/FixedPointNumber.unit.test.ts
The tests at `packages/core/tests/vcdm/FixedPointNumber.unit.test.ts` adapted to updated **jest** paradigm to compare approximated results of IEEE-754 floating point numbers and fixed point numbers. 
Fixes #2158
* Node.js Version: v24.0.0
=> 2158 fixed precision number tests fix

packages/sdk/package.json, packages/sdk/src/common/http/FetchHttpClient.ts, packages/sdk/src/thor/thor-client/ThorClient.ts, packages/sdk/src/thor/thor-client/gas/gas-module.ts, packages/sdk/src/thor/thorest/accounts/response/ExecuteCodesResponse.ts, packages/sdk/src/viem/clients/Contract.ts, packages/sdk/tests/thor/thorest/accounts/InspectClauses.solo.test.ts, packages/sdk/tests/thor/thorest/accounts/InspectClauses.unit.test.ts, packages/sdk/tests/viem/clients/publicClient/contracts.solo.test.ts, packages/sdk/tests/viem/clients/publicClient/fees.solo.test.ts
- Fixes the solo tests
- Change to FetchHttpClient so that abort signal can be used in a `finally` --> this closes approx 13 jest warnings about open handles
* Node.js Version: v22
* Yarn Version: v1
=> Fix solo tests, add detect open handles

packages/sdk/src/common/logging/JSONLogger.ts, packages/sdk/src/common/logging/PrettyLogger.ts, packages/sdk/src/common/logging/types.ts, packages/sdk/tests/common/logging/jsonlogger.unit.test.ts, packages/sdk/tests/common/logging/prettylogger.unit.test.ts
Fixes the inbuilt json and pretty loggers to log `bigint` types in context paraemeter
* Node.js Version: v22
* Yarn Version: v1
=> fix: logger bigint
